---
title: "EDA_Joe"
author: "Joseph May"
date: "April 24, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup}
library(tidyverse)
library(stringr)
phanalytix <- read.csv('phanalytix.csv', stringsAsFactors = FALSE)
significance <- read.csv('significance.csv', stringsAsFactors = FALSE)
```

```{r Significance, eval = FALSE}
#length minus regular length
#Parse Song Time as seconds
song_length <- tibble(minutes = str_extract_all(phanalytix$duration_song, "[0-9]+(?=:)"), 
                      seconds = str_extract_all(phanalytix$duration_song, "(?<=:)[0-9]+")) %>% 
    mutate(minutes = as.numeric(minutes), 
           seconds = as.numeric(seconds))

phanalytix <- mutate(phanalytix, song_seconds = (song_length$minutes*60+song_length$seconds))


##Song Rotation: The percentage of times the show is played
#Count the number of shows played
numOfShows <- dim(
                summarise(
                    group_by(
                        significance, date)))[1]
#Add the ratio to the phanalytix dataset
significance <- significance %>% 
    mutate(rotation = total_times_played/numOfShows)


##Add in the Significance Metrics
significance <-  significance %>% 
        #Length Rating
        mutate(length_rating = song_seconds/max(significance$song_seconds, na.rm = TRUE),
               #Gap Rating
               gap_rating = adj_gap/max(significance$adj_gap, na.rm = TRUE),
               #Rotation Rating
               rotation_rating = 1 - rotation/max(significance$rotation, na.rm = TRUE),
               #Rating Rating
               rating_rating = ratings/max(significance$ratings, na.rm = TRUE),
               #Debut Rating
               date = parse_date(date),
               debut = parse_date(debut),
               # since_debutThen = ifelse(as.numeric(date - debut) > 0, as.numeric(date - debut), 0),
               # since_debutNow = ifelse(as.numeric(Sys.Date() - debut) > 0, as.numeric(Sys.Date() - debut), 0),
               # since_debutThen_rating = since_debutThen/max(significance$since_debutThen, na.rm = TRUE),
               # since_debutNow_rating = since_debutNow/max(significance$since_debutNow, na.rm = TRUE),
               # since_debut_rating = (since_debutThen_rating + (since_debutNow_rating*5))/6,
               showAge = ifelse(as.numeric(Sys.Date() - date) > 0, as.numeric(Sys.Date() - date), 0),
               showAge_rating = showAge/max(showAge, na.rm = TRUE),
               #Debut Dummy Bonus
               debut_dummy = as.numeric(grepl('debut|first known', notes)),
               #Tease Dummy Bonus
               tease_dummy = as.numeric(grepl('tease|quote', notes)),
               #Notes Bonus
               notes_dummy = as.numeric(grepl('[qwertyuiopasdfghjklzxcvbnm]', notes)) 
                            - debut_dummy - tease_dummy, 
               notes_dummy = ifelse(notes_dummy<0, 0, notes_dummy)
        ) %>% 
    select(-showAge)


#Different People Value things differently, Here we can input our preferences.
lengthValue <- 3/15
gapValue <- 4/15
rotationValue <- 2/15
ratingValue <- 5/15
sinceDebutValue <- 1/30
coverBonus <- 0.02
debutBonus <- 0.01
notesBonus <- 0.03
teaseBonus <- 0.04

#Final Significance Rating
significance <- significance %>% 
    mutate(significance_rating = length_rating*lengthValue +
                                 gap_rating*gapValue +
                                 rotation_rating*rotationValue +
                                 rating_rating*ratingValue +
                                 since_debut_rating*sinceDebutValue +
                                 cover_dummy*coverBonus +
                                 debut_dummy*debutBonus +
                                 notes_dummy*notesBonus +
                                 tease_dummy*teaseBonus)

bestShows <- significance %>% 
    group_by(date) %>% 
    summarise(avgRating = mean(significance_rating, na.rm = TRUE))

# significance <- significance %>% 
#     mutate(significance_rating = ifelse(is.na(length_rating*lengthValue), 0, 
#                                         length_rating*lengthValue) +
#                                  ifelse(is.na(gap_rating*gapValue), 0, 
#                                         gap_rating*gapValue) +
#                                  ifelse(is.na(rotation_rating*rotationValue), 0, 
#                                         rotation_rating*rotationValue) +
#                                  ifelse(is.na(rating_rating*ratingValue), 0, 
#                                         rating_rating*ratingValue) +
#                                  ifelse(is.na(since_debut_rating*sinceDebutValue), 0, 
#                                         since_debut_rating*sinceDebutValue) +
#                                  ifelse(is.na(cover_dummy*coverBonus), 0, 
#                                         cover_dummy*coverBonus) +
#                                  ifelse(is.na(debut_dummy*debutBonus), 0, 
#                                         debut_dummy*debutBonus) +
#                                  ifelse(is.na(notes_dummy*notesBonus), 0, 
#                                         notes_dummy*notesBonus))

ggplot(significance) +
    geom_histogram(aes(significance_rating))

mean(significance$length_rating, na.rm = TRUE)
mean(significance$gap_rating, na.rm = TRUE)
mean(significance$rotation_rating, na.rm = TRUE)
mean(significance$rating_rating, na.rm = TRUE)
mean(significance$since_debut_rating, na.rm = TRUE)


write_csv(significance, 'significance.csv')
significance <- read.csv('significance.csv', stringsAsFactors = FALSE)
```

```{r final EDA3}
# significance %>% 
#     group_by(date, ratings) %>% 
#     summarise(avgGap = mean(adj_gap), debut = mean(since_debut)) %>% 
#     arrange(desc(avgGap)) %>% 
#     ggplot() +
#     geom_jitter(aes(avgGap, ratings, color = debut)) +
#     geom_smooth(aes(avgGap, ratings), method = 'lm') +
#     scale_color_gradientn(colors = c('sky blue', 'black')) +
#     ggtitle("Songs that are played less often are usually percieved as special and better") +
#     xlab("Average number of shows that passed until the song was played again") +
#     ylab("Rating from Phish.Net")

significance %>% 
    mutate(days_since_debut = since_debut) %>% 
    ggplot() +
    geom_jitter(aes(adj_gap, ratings, color = days_since_debut), na.rm = TRUE, width = .5) +
    geom_smooth(aes(adj_gap, ratings), method = 'lm', na.rm = TRUE, se = FALSE, color = 'Red') +
    scale_color_gradientn(colors = c('sky blue', 'black')) +
    ggtitle("Shows which include rarely performed songs are percieved as better") +
    xlab("Number of shows passed between live performances") +
    ylab("Rating from Phish.Net")

#There are many factors that go into what making phish shows and songs special to concert-goers. One that interests me is songs that are considered 'rare', people that follow the tour closely know what hasnt been played, and anytime something is busted out, the crowd usually picks up on it very quickly, even if the song hasnt been played in 10-20 years. This chart groups the data by show, and summarises the average song gap for that concert (where we want large outliers to skew the mean upwards), the rating from Phish.Net, and the days since the song was debuted when it was performed. It shows that concerts with high average song gaps generate significantly higher phish.net ratings with only one significant outlier. We also include days since the debut as a color pattern, because more recent sons havnt had the opportunity to have been held for a while to bust out later, so the color seeks to point out that confounding factor.
```

```{r final EDA5}
# significance %>% 
#     group_by(date) %>% 
#     summarise(number_of_shows_per_tour = n(), 
#               Average_Significance_Rating = mean(significance_rating, na.rm = TRUE), 
#               rating = mean(ratings)) %>% 
#     ggplot() +
#     geom_jitter(aes(date, rating, color = number_of_shows_per_tour), width = .1) +
#     scale_color_gradientn(colors = c('sky blue', 'black')) +
#     geom_smooth(aes(date, rating), color = 'red') +
#     ggtitle("How the percieved quality of shows has changed over time") +
#     xlab("Year") +
#     ylab("Average Rating from Phish.Net")


text_df <- tibble(x = c(2001.5,2007), y = c(5,2), text = c('Two Year Hiatus', 'Four Year Break-Up'))
significance %>% 
    group_by(date, year) %>% 
    summarise(avg_rating = mean(ratings)) %>% 
    ggplot() +
    geom_jitter(aes(year, avg_rating), width = .3, height = .4) +
    geom_smooth(aes(year, avg_rating)) +
    ylim(0,5) +
    scale_x_continuous(breaks=seq(from=1980, to=2020, by=5)) +
    ggtitle("How the percieved quality of shows has changed over time") +
    xlab("Year") +
    ylab("Average Rating from Phish.Net") +
    geom_text(data = text_df, aes(x=x, y=y, label = text), color = 'red')

#Though Phish has kept the original members for the entirety of the band's existance, they have have gone through many aristic phases. Objectively speaking, their career is broken into three chunks: 1.0 is from 1984 until 2000, when they went on a hiatus. 2.0 from 200 until 2004 when they broke up indefinitely. Lastly, 3.0 from 2009 until now, when they got back together. Each phase has has very different sounds, improvisational styles, and lifestyle influences that have moulded their live sound, and each era has fans and doubters. This chart maps each year's shows and maps them with the average of ratings from Phish.Net.
```

```{r EDA1}
significance %>% 
    group_by(date, ratings) %>% 
    summarise(debuts = sum(debut_dummy)) %>% 
    arrange(desc(debuts)) %>% 
    ggplot() +
    geom_smooth(aes(x = debuts, y = ratings)) +
    geom_jitter(aes(x = debuts, y = ratings)) +
    ggtitle('How the number of first time song performances in a show affect percieved quality') +
    xlab('Number of live Debuts in one night') +
    ylab("Rating from Phish.Net")


# ggtitle() +
#     xlab() +
#     ylab()
```

```{r EDA2}
# significance %>% 
#     mutate(notesExc = notes_dummy - debut_dummy - cover_dummy,
#            ifelse(notesExc < 0, 0, notesExc)) %>% 
#     group_by(date, ratings) %>% 
#     summarise(notes = sum(notesExc)) %>% 
#     arrange(desc(notes)) %>% 
#     ggplot() +
#     geom_jitter(aes(notes, ratings)) +
#     geom_smooth(aes(notes, ratings))
#     ggtitle() +
#     xlab() +
#     ylab()

    
significance %>% 
    group_by(date, ratings) %>% 
    summarise(teases = sum(tease_dummy)) %>% 
    arrange(desc(teases)) %>% 
    ggplot() +
    geom_jitter(aes(teases, ratings), width = .5, height = .2) +
    geom_smooth(aes(teases, ratings), method = 'lm') + 
    ggtitle('How the number song teases/quotes in a show affect percieved quality') +
    xlab('Number of times Phish played one song inside of another during a show') +
    ylab("Rating from Phish.Net")

    #This Takes the variable that checks to see if the "Notes" variable includes the words "tease" or "quote", meaning that they played bits of one song inside of another. This musical action was frequent in the late 90's and is less often now, often times they would interweave countles songs, inside of one songs structure, while carrying that song for extended periods of time. These performances, when executed well, are very intersting, and this chart shows that concerts with the highest number of teases and quotes are related to a higher average rating on Phish.Net
```

```{r EDA4}
phanalytix %>% 
    group_by(date, ratings) %>% 
    summarise(covers = sum(cover_dummy)) %>% 
    arrange(desc(covers)) %>% 
    ggplot() +
    geom_jitter(aes(covers, ratings)) +
    geom_smooth(aes(covers, ratings)) +
    ggtitle("Every year Phish covers an entire album from an artist that has inspired them, so how does the number of covers in a show effect it's percieved quality") +
    xlab("Number of covers in a single concert") +
    ylab('Rating from Phish.Net')
    
#Go in and highlight halloween shows
```

```{r EDA6}
#This new significance metric takes into account the length of the song, how long it had been since it was played, how often it is played, how long phish has been playing that song for, was it performed for the first time, covers, and phish.net rating
#Note, not all shows have this many sections, the standard sow is just two sets and an encore.

significance %>% 
    group_by(set_name) %>% 
    summarise(Average_Significance_Rating = mean(significance_rating, na.rm = TRUE), n()) %>% 
    ggplot() +
    geom_point(aes(set_name, Average_Significance_Rating)) +
    scale_x_discrete(limits = c("Soundcheck", "Set 1", "Set 2", "Set 3", "Set 4", "Encore", "Encore 2", "Encore 3")) +
    ggtitle('How average significance moves throughout the different parts of the show') +
    xlab("Set Name (Note: Only special shows have more than Two Sets and Two Encores") +
    ylab("Average Significance Rating")
    
#     ggtitle() +
#     xlab() +
#     ylab()

```

```{r EDA7}
significance %>% 
    group_by(song, total_times_played) %>% 
    summarise(meanSignificanceRating = mean(significance_rating, na.rm = TRUE), 
              debut = mean(since_debut), 
              rating = mean(ratings))%>% 
    ggplot() +
    geom_jitter(aes(total_times_played, rating, color = debut)) +
    geom_smooth(aes(total_times_played, rating),method = 'lm') +
    scale_color_gradientn(colors = rainbow(2)) +
    ggtitle("Songs That are played the most, are othen the least significant") +
    xlab("Total Times A Song Has Been Played") +
    ylab("Rating from Phish.Net")

#redo exluding gap and rotation or maybe with phish.net

```

```{r EDA8}
significance %>% 
    group_by(state) %>% 
    summarise(rating = mean(ratings, na.rm = TRUE), number = n()) %>% 
    arrange(desc(rating)) %>% 
    mutate(correlation = cor(rating, number, use = 'everything')) %>% 
    ggplot() +
    geom_jitter(aes(rating, number)) +
    geom_smooth(aes(rating, number)) +
    ggtitle("Some states get more shows than others: how does the freuqnecy of phish performances effect") +
    xlab('Rating from Phish.Net') +
    ylab('Number of Shows Played in that State')


```

```{r EDA9}
significance <- significance %>% 
    mutate(less_ratings_significance_rating = length_rating*lengthValue +
                                 gap_rating*gapValue +
                                 rotation_rating*rotationValue +
                                 since_debut_rating*sinceDebutValue +
                                 cover_dummy*coverBonus +
                                 debut_dummy*debutBonus +
                                 notes_dummy*notesBonus)


 significance %>% 
    group_by(id_show) %>% 
    summarise(Average_Significance_Rating = mean(significance_rating, na.rm = TRUE),
               AdjAverage_Significance_Rating = mean(less_ratings_significance_rating, na.rm = TRUE),
                meanRating = mean(ratings, na.rm = TRUE)) %>% 
    ggplot() +
    geom_point(aes(meanRating, AdjAverage_Significance_Rating)) +
    geom_smooth(aes(meanRating, AdjAverage_Significance_Rating), color = 'Red') +
    ggtitle("How does a combiend metric of Song Duration, Song Gap, Rotation, Age of a Song, Covers, and Song Teases relate to Phish.Net Ratings") +
    xlab('Rating from Phish.Net') +
    ylab('Adjusted Significance Metric (Excluding Phish.Net Rating)')


# significance %>% 
#     group_by(id_show) %>% 
#     summarise(Average_Significance_Rating = mean(significance_rating, na.rm = TRUE),
#                AdjAverage_Significance_Rating = mean(less_ratings_significance_rating, na.rm = TRUE),
#                 meanRating = mean(ratings, na.rm = TRUE)) %>% 
#     ggplot() +
#     geom_point(aes(AdjAverage_Significance_Rating, meanRating, color = Average_Significance_Rating)) +
#     geom_smooth(aes(AdjAverage_Significance_Rating, meanRating), color = 'Red')
```

```{r EDA10}
#Two correlations for how Song Duration, Song Gap, Song Rotation, Days Since it was Debuted, Notes, and Covers have predictive power on Phish.Net ratings. All of the variables are significant and generated a very significant F statistic. One regression is on the 0-1 variables ranking each category, and the second regression is on the raw, non-normalized values. For the normalized regression, it is interesting to note that Length and Gap have the largest correlation coeficcients, with covers being the lowest, while rotation and days since debut are the most significant.
lm(ratings ~ 
           length_rating + gap_rating + rotation_rating + since_debut_rating + notes_dummy + cover_dummy,     significance) %>% 
    summary()

lm(ratings ~ 
           song_seconds + adj_gap + rotation + since_debut + notes_dummy + cover_dummy, significance) %>% 
    summary()
  
```
